### ISSUE TITLE
生成令牌文件报错

### ISSUE THREAD

**Issue by 470245139** [ShaderFallback/KindleOutlookCalendarWeather#10]
=================Outlook令牌生成工具===================

请提前在config.ini文件填写客户端ID,和密码的值

复制下面的连接到浏览器,并登录邮箱授权,然后将浏览器链接粘贴回来,并回车

-注意不要有任何多余空格和符号!

------------------BiliBili日出东水---------------------

Visit the following url to give consent:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=6fd66d9a-a956-4862-8341-201fb8b928ad&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient&scope=https%3A%2F%2Fgraph.microsoft.com%2FCalendars.ReadWrite+https%3A%2F%2Fgraph.microsoft.com%2FUser.Read+offline_access&state=KE1JQq8bXBiQ3pkE8fgmnaj4vgmS9L&access_type=offline
Paste the authenticated url here:
https://login.microsoftonline.com/common/oauth2/nativeclient?code=M.C531_BAY.2.U.8900c53b-554f-8c35-adba-2f3e1553be4a&state=g1dLuUqwEkbZaKX27EY4j6SJXo5XDE
Unable to fetch auth token. Error: (mismatching_state) CSRF Warning! State not equal in request and response.
Something go wrong. Please try again.
O365\utils\utils.py:905: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
Traceback (most recent call last):
  File "PythonO365.py", line 90, in <module>
  File "PythonO365.py", line 61, in GetO365
  File "O365\calendar.py", line 1899, in get_events
  File "O365\calendar.py", line 1651, in get_events
  File "O365\connection.py", line 654, in get
  File "O365\connection.py", line 641, in oauth_request
  File "O365\connection.py", line 449, in get_session
RuntimeError: No auth token found. Authentication Flow needed
[7084] Failed to execute script 'PythonO365' due to unhandled exception!

**Comment by 470245139** [comment]
电脑可以访问login.microsoftonline.com。

**Comment by ShaderFallback** [comment]
令牌工具已经更新,下载新版本即可
https://github.com/ShaderFallback/KindleOutlookCalendarWeather/releases/tag/1.0.1
