### ISSUE TITLE
微软不让注册app了，应该怎么解决？

### ISSUE THREAD

**Issue by maxway** [ShaderFallback/KindleOutlookCalendarWeather#13]
![image](https://github.com/user-attachments/assets/a4f1ef5b-319a-4dad-990b-de36c4bc051c)
![image](https://github.com/user-attachments/assets/d0bdec19-ec4c-44f7-9adc-bb603cb06961)

**Comment by ShaderFallback** [comment]
刚才试了是可以注册的，尝试注册一个 outLook邮箱？ 

![图片](https://github.com/user-attachments/assets/a8f30fd2-4dd4-40fb-a5d3-b46abf8aabcd)

**Comment by maxway** [comment]
也就是现在使用Azure了，看了看免费12个月，之后不知道需不需要付费。
 ps：我改了直接从表里读数据，不从outlook拉数据，直接fork了一个项目。

**Comment by ShaderFallback** [comment]
他应该是一直免费的，我这个都注册好几年了
