### ISSUE TITLE
同步日程报错

### ISSUE THREAD

**Issue by ruhuasiyi** [ShaderFallback/KindleOutlookCalendarWeather#15]
log.log报错Update Schedule..Fail!“Etc/GMT”，参照[](https://github.com/ShaderFallback/KindleOutlookCalendarWeather/issues/12) 将tzname = "Etc/GMT" 修改为 tzname = "Asia/Shanghai"后报错Update [Schedule..Fail!“Asia/Shanghai”，检查发现/usr/share/zoneinfo中只有iso3166.tab  zone.tab两个文件，从别的linux中拖了个Shanghai到/usr/share/zoneinfo/Asia/ 中，重新运行，报错Update Schedule..Fail!'_PytzShimTimezone' object has no attribute 'key'

Kindle型号位KPW3，系统版本5.15.1.1

**Comment by ShaderFallback** [comment]
让默认返回值为 tz = timezone.utc   试试,看能否正常运行  (稍后在解决时区转换问题

**Comment by ShaderFallback** [comment]
没有反馈就关闭这个单了
