### ISSUE TITLE
文字显示不全

### ISSUE THREAD

**Issue by renchili** [ShaderFallback/KindleOutlookCalendarWeather#3]
![image](https://github.com/ShaderFallback/KindleOutlookCalendarWeather/assets/33677006/ea02427c-64ee-4ce8-a829-1fab8aa3d1cf)
Rss下面的文字显示不全

**Comment by ShaderFallback** [comment]
这是正常的, 因为显示区域不够只能裁剪, 如果通过字符数量进行裁剪文字中有特殊字符或中英混合无法获得整句话稳定宽度, 最后采用的方式是通过Mask 去按像素裁剪可以准确的裁剪到可显示区域内
