### ISSUE TITLE
非刷新天气时间进入程序天气不刷新

### ISSUE THREAD

**Issue by renchili** [ShaderFallback/KindleOutlookCalendarWeather#5]
https://github.com/ShaderFallback/KindleOutlookCalendarWeather/blob/651b66d53ac6ef1c56beac3ac8d10fc53116739e/bin/WeatherStation.py#L235

需要判断当前是否有天气缓存没有的话需要重新建立

**Comment by maxway** [comment]
我记得启动的时候有一次拉取天气数据的

**Comment by renchili** [comment]
![image](https://github.com/user-attachments/assets/c74d53d2-11a1-4d5e-94a0-b8a6b0267edd)
zhe'li这里的 update 是不是没有什么用 你虽然从天气平台拉取了 天气 但是你存到 return的变量里面了 然后你对return的内容啥也没做

**Comment by maxway** [comment]
global了变量，不return也修改了。
