### ISSUE TITLE
逻辑混乱

### ISSUE THREAD

**Issue by renchili** [ShaderFallback/KindleOutlookCalendarWeather#6]
https://github.com/ShaderFallback/KindleOutlookCalendarWeather/blob/651b66d53ac6ef1c56beac3ac8d10fc53116739e/bin/WeatherStation.py#L561

为什么要在 GetRss 的 死循环里面引用更新天气？

**Comment by ShaderFallback** [comment]
因为需要一个时机来刷新天气，要么启动一个新线程定期刷新，要么放在一个时间循环中，每分钟刷新一次。
RSS每2小时刷新一次，时间刚刚好，而且更新天气的函数已经做了保护，API每天只会请求4次，所以不用担心


    intTime = int(strtime5)

    if(countUpdate_1 and  intTime == 7):
        tempArray = UpdateData()
        countUpdate_1 = False
    elif(countUpdate_2 and intTime == 11):
        tempArray = UpdateData()
        countUpdate_2 = False
    elif(countUpdate_3 and intTime == 16):
        tempArray = UpdateData()
        countUpdate_3 = False
    elif(countUpdate_4 and intTime == 21 ):
        tempArray = UpdateData()
        countUpdate_4 = False

**Comment by SparkCD** [comment]
> 因为需要一个时机来刷新天气，要么启动一个新线程定期刷新，要么放在一个时间循环中，每分钟刷新一次。 RSS每2小时刷新一次，时间刚刚好，而且更新天气的函数已经做了保护，API每天只会请求4次，所以不用担心
> 
> ```
> intTime = int(strtime5)
> 
> if(countUpdate_1 and  intTime == 7):
>     tempArray = UpdateData()
>     countUpdate_1 = False
> elif(countUpdate_2 and intTime == 11):
>     tempArray = UpdateData()
>     countUpdate_2 = False
> elif(countUpdate_3 and intTime == 16):
>     tempArray = UpdateData()
>     countUpdate_3 = False
> elif(countUpdate_4 and intTime == 21 ):
>     tempArray = UpdateData()
>     countUpdate_4 = False
> ```

问一下  怎么更改天气刷新的时间   我这早上上班还是昨天的天气    我改了里边的7 11 16 21没有作用

**Comment by SparkCD** [comment]
还有就是 天气刷新逻辑混乱  我两个rss切换的时候 一个天气刷新了  一个天气还是老的   😵
