### ISSUE TITLE
天气图标缺少 与其他天气app数据差别较大   RSS源只能添加两个？

### ISSUE THREAD

**Issue by SparkCD** [ShaderFallback/KindleOutlookCalendarWeather#8]
天气图标缺少霾      天气数据不准确     RSS源添加两个以上  打开软件会一直白屏

**Comment by ShaderFallback** [comment]
1. 我在南方基本见不到这些类型 = =！ ,这些类型统一会使用 sandstorm.bmp
elif(tempType == "沙尘暴" or tempType == "浮尘" or
        tempType == "扬沙" or tempType == "强沙尘暴" or
        tempType == "雾霾"):
        return "sandstorm.bmp"

2. 你也可以换成其他天气API 修改 GetTemp() 这个方法
3. 新闻目前时只有两个源轮播(写死的)

**Comment by SparkCD** [comment]
好的 好的   清楚了 蟹蟹你的回复     还有个问题  你天气貌似写错了  明天天气是今天的  后天的是明天的

**Comment by SparkCD** [comment]
``def WeatherStrSwitch(index):
    if index == 1:
        return"明天"
    elif index == 2:
        return"后天"
    elif index == 3:
        return"大后天"
改成这样就对了

**Comment by SparkCD** [comment]
改了之后会白屏进不去   再救救我

**Comment by SparkCD** [comment]
还有不知道为什么  你写的这些类型统一会使用 sandstorm.bmp
elif（tempType == “沙尘暴” 或 tempType == “浮尘” 或 tempType == “扬沙” 或 tempType == “强沙尘暴” 或

tempType == “雾霾”）：
return “sandstorm.bmp”      但是我这里图像显示的还是一个云朵一个问号

**Comment by SparkCD** [comment]
雾霾应该改成霾    api接口返回的是这个   我说我的霾 咋是问号 哈哈

**Comment by SparkCD** [comment]
> 好的 好的 清楚了 蟹蟹你的回复 还有个问题 你天气貌似写错了 明天天气是今天的 后天的是明天的
def WeatherSwitch(index):
    if index == 0:
        return 9
    elif index == 1:
        return 14
    elif index == 2:
        return 19
我修改成这样了
