### ISSUE TITLE
天气刷新的问题

### ISSUE THREAD

**Issue by SparkCD** [ShaderFallback/KindleOutlookCalendarWeather#9]
```
intTime = int(strtime5)

if(countUpdate_1 and  intTime == 7):
    tempArray = UpdateData()
    countUpdate_1 = False
elif(countUpdate_2 and intTime == 11):
    tempArray = UpdateData()
    countUpdate_2 = False
elif(countUpdate_3 and intTime == 16):
    tempArray = UpdateData()
    countUpdate_3 = False
elif(countUpdate_4 and intTime == 21 ):
    tempArray = UpdateData()
    countUpdate_4 = False
```

问一下 怎么更改天气刷新的时间 我这早上上班还是昨天的天气 我改了里边的7 11 16 21没有作用
还有就是 天气刷新逻辑混乱 我两个rss切换的时候 一个天气刷新了 一个天气还是老的 😵

**Comment by ShaderFallback** [comment]
这个地方时间转换为了 int 值 
7 就是 早上7 点 
21 就是晚上 9 点
不过这个天气API 只有这几个点会更新,具体可以取SoJson 网站查阅

**Comment by ShaderFallback** [comment]
1.只有一个天气，两个天气混乱指的是什么？
2.天气API刷新时间为每天7,11,16,21点左右所以在这个时间点会请求一次，由于受限于免费API有可能更新失败，可以尝试再延迟一小时如8,12,17,22，减少服务器压力，避开请求高峰
3.具体可以查看log确定是否正常更新

在 2024年1月15日星期一，SparkCD ***@***.***> 写道：
